hatchways/team-daffodil

client/src/pages/Register.js

Accidentally left an extra render() function when merging another branch to dev

remove extra render()

---

client/src/pages/Register.js
client/src/themes/theme.js

Feature register client

---

client/package.json
client/src/components/NavBar.js
client/src/pages/Login.js
client/src/pages/Profile.js
client/src/pages/Register.js
client/src/themes/theme.js

- Redid this branch from scratch because we had issues with the last one.

Feature save jwt tokens to local storage on client

---

client/src/components/UserEditDialog.js
client/src/components/UserPanel.js

- set up the user edit dialog window
- displaying the current location, description of the user
- can upload profile image

Feature profile edit client

---

client/package-lock.json
client/src/App.js
client/src/components/NavBar.js
client/src/pages/Login.js
client/src/pages/Profile.js
client/src/pages/Register.js
server/db.js
server/models/userModel.js
server/package.json
server/routes/loginRoute.js
server/routes/userRoute.js
server/validate/validateExisting.js
server/validate/validateNew.js

- added username fields client side and server side
- login done through username instead of email

Feature add username field

---

client/src/components/AudioRecord.js
client/src/components/NavBar.js
client/src/components/UserPanel.js
client/src/pages/CreateConversation.js
client/src/pages/Login.js
client/src/pages/Profile.js
client/src/pages/Register.js

- fixed navbar so username properly displays on it
- added username to user profile panel

Feature navbar username fix

---

client/package-lock.json
server/app.js
server/config/default.json
server/routes/userRoute.js
server/services/fileUpload.js

EDIT: nothing was wrong with my code. I had to restart postman to get it to work
I am using multer and multer s3 to upload profile pictures on Amazon S3. On line 103 of the put route handler(in userRoute.js), i'm returning the req.file.location to get the url of the uploaded image.However, I keep getting an error saying that the location property is undefined. Can someone please help me with this? Thank you.

pic upload fixed

---

.gitignore
client/src/components/UserEditDialog.js
client/src/components/UserPanel.js
client/src/pages/Profile.js
server/app.js
server/config/custom-environment-variables.json
server/config/default.json
server/db.js
server/models/userModel.js
server/routes/userRoute.js

profile pic can now be edited and displayed.

Feature display pic

---

client/src/components/ConversationDialog.js
client/src/components/UserPost.js
client/src/pages/CreateConversation.js

added a dialog when a user selects a conversation on the profile page

Feature conversation dialog

---

client/src/components/UserPanel.js
client/src/pages/Profile.js
server/db.js

- set default profile pic if user has none
- added gray placeholder text for location and description if not set
- added location icon
- fixed spacing

Fixed up userpanel in profile page

---

client/src/components/AddPost.js
client/src/components/ConversationDialog.js
client/src/components/UserPanel.js
client/src/pages/Profile.js

- now generate the real posts of the user on their profile page
- panel to create their first convo appears if they have not made a conversation

Feature generate actual userposts 

---

client/package.json
client/src/components/AudioPlayer.js
client/src/components/ConversationDialog.js
client/src/components/UserPost.js
client/src/pages/Profile.js
client/yarn.lock

currently can't play back audio from s3 using the audio-player. But can play it back with the HTML audio element

Feature audio player

---

client/package-lock.json
client/src/App.js
client/src/components/AudioPlayer.js
client/src/components/ConversationDialog.js
client/src/components/FeedUser.js
client/src/components/NavBar.js
client/src/pages/Feed.js
server/db.js
server/models/conversationModel.js
server/routes/userRoute.js

Feature feed client

---

client/package-lock.json
client/src/App.js
client/src/components/FeedUser.js
client/src/components/NavBar.js
client/src/pages/Feed.js
server/db.js
server/models/conversationModel.js
server/routes/userRoute.js

Changes in this branch:
- API endpoint to fetch all conversations
- Feed Page(needs styling)
- Feed User Info component(needs styling)

conversation feed setup(feature-feed-server)

---

client/src/components/FeedUser.js
client/src/pages/Feed.js
server/db.js
server/models/conversationModel.js

- on the backend now store username profile imageUrl on each conversation.

add username and picture on conversations in the feed

---

client/src/components/ConversationDialog.js
client/src/components/ConversationPost.js
client/src/components/FeedUser.js
client/src/components/ReplyDialog.js
client/src/components/UserPost.js
client/src/pages/CreateConversation.js
client/src/pages/Profile.js

- When user clicks the reply button, a dialog box pops up for the user to record a response

Added reply dialog 

---

client/src/components/ConversationDialog.js
client/src/components/ConversationPost.js
client/src/components/FeedUser.js
client/src/components/ReplyDialog.js
client/src/components/UserPost.js
client/src/pages/CreateConversation.js
client/src/pages/Feed.js
client/src/pages/Login.js
client/src/pages/Profile.js
client/src/pages/Register.js
server/db.js

The following changes were made:
-created a new Comments collection
-Comments are referenced inside an array of a conversation document
-made http POST request on the client side to post a new comment

user can now  comment

---

client/src/components/ConversationDialog.js
client/src/components/ConversationPost.js
client/src/pages/Feed.js
client/src/pages/Profile.js

Work in progress, currently what happens:
- display a template for the comments that made
- the audio is real but the user info is just placeholders
- need to reload page to show new comments

set up basic comment ui

---

client/src/components/ConversationDialog.js
client/src/components/ConversationPost.js
client/src/components/ReplyDialog.js
client/src/pages/Feed.js
client/src/pages/Profile.js
server/db.js
server/routes/userRoute.js

- Now comments have the real user information attached to them
- new likes and comments are now visible immediately (without a page load!)
- display number of comments
- updates to backend to get a single conversation and deeper populates

Feature fixed up up comments and likes

---

client/src/App.js
client/src/components/ConversationDialog.js
client/src/components/ConversationPost.js
client/src/components/NavBar.js
client/src/components/ReplyDialog.js
client/src/components/UserPanel.js
client/src/pages/CreateConversation.js
client/src/pages/Feed.js
client/src/pages/Login.js
client/src/pages/Profile.js
client/src/pages/Register.js
server/db.js
server/models/conversationModel.js
server/routes/userRoute.js

- updated profile routing to '/profile/:id'
- now the logged in user can visit other profile pages
- still need to make other's profile pages un-editable

Feature visit other profile pages
